In [11]:
import pandas as pd
import numpy as np 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

#Removing entries for genres with less volume and dropping insignificant columns
data = pd.read_csv('songs.csv')
data['title'].drop_duplicates()
data['top genre'].value_counts()
t = data['top genre'].value_counts()
filtered = data.groupby('top genre').filter(lambda x : len(x)>12)
filtered = filtered.drop(columns = ['target', 'artist', 'added'])
filtered = filtered.drop_duplicates(['title'])
filtered.shape

(98, 13)

In [12]:
#Map categorical variables to numeric

filtered['top genre'].value_counts()
filtered['top genre'] = filtered['top genre'].map({'desi pop': 0, 'dance pop': 1, 'hip hop': 2, 'emo rap': 3, 'conscious hip hop': 4})
filtered

title  top genre  year  bpm  \
0                                            Aur Tanha          0  2020  170   
2                                              Mehrama          0  2020  108   
10                                             Control          0  2020   99   
14                                  Andhadhun Theme 02          0  2018  138   
15                    Pal Pal Dil Ke Paas- Title Track          0  2019  124   
16                                            Wo Ladki          0  2018  130   
17                     Naina Da Kya Kasoor - Unplugged          0  2018  126   
18                         Jaane Kyun (From "Dostana")          0  2013  100   
25   Chal Ghar Chalen (From "Malang - Unleash The M...          0  2020  180   
26                        Shayad (From "Love Aaj Kal")          0  2020  136   
27         Tu Hi Yaar Mera (From "Pati Patni Aur Woh")          0  2019   87   
28                                            How Long          1  2018  110   
29                                           Attention          1  2018  100   
30                                        The Way I Am          1  2018  115   
31                                              Nakhre          0  2015  170   
33                                    Don't Call Me Up          1  2019   99   
35           Arms Around You (feat. Maluma & Swae Lee)          3  2018  105   
38                                            Ghungroo          0  2019  118   
40                                             Befikra          0  2016  137   
42                                     Love Controller          0  2016  102   
43                           Naah Goriye (From "Bala")          0  2019  100   
44                                  Crying in the Club          1  2017   85   
45                 Dilbara (From "Pati Patni Aur Woh")          0  2019   90   
46                                 Main Tera Boyfriend          0  2017  104   
47                    O Saki Saki (From "Batla House")          0  2019  108   
48           Dheeme Dheeme (From "Pati Patni Aur Woh")          0  2019  110   
50                                            Everyday          4  2018  150   
51                                            Mad Love          1  2018   98   
54                                            Bairaagi          0  2017   80   
55                                     I Warned Myself          1  2019  184   
56                                            Gotta Go          0  2019  103   
61                      Bekhayali (From "Kabir Singh")          0  2019  172   
62                                     Bom Diggy Diggy          0  2018  104   
63                          Photo (From "Luka Chuppi")          0  2019   95   
64                                         First Class          0  2019  188   
65                                         Ik Mulaqaat          0  2019   96   
66          We Don't Talk Anymore (feat. Selena Gomez)          1  2016  100   
67                               Ik Mulaqaat Unplugged          0  2019   94   
69                                               Safar          0  2017   86   
70                                     Cheating on You          1  2019  123   
71                                       Main Kya Hoon          0  2009  135   
83                                           Bom Diggy          0  2017  104   
84                                            LA Girls          1  2018  100   
88                                       Lakk Mera Hit          0  2018  115   
89                                   Chhote Chhote Peg          0  2018  105   
91                      Coca Cola (From "Luka Chuppi")          0  2019  102   
92                                                Vele          0  2012  108   
94                                   Saturday Saturday          0  2014  130   
95                                    The Breakup Song          0  2016  114   
96                         Twist (From "Love Aaj 

In [32]:
#train test split and scale the variables
scale = StandardScaler()
pd.set_option('display.max_rows', None)
x = filtered[list(filtered.columns[0:14])]
y = filtered[list(filtered.columns[1:2])]
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.2, random_state = 1)
print(x_train)
x_train = x_train.drop(columns=['top genre'])
x_test = x_test.drop(columns=['top genre'])
print(x_train.head(98))
dataPoints = {}
x_train = x_train.reset_index()
x_test = x_test.reset_index()
for i in range(0,len(x_train)):
    title = x_train['title'][i]
    info = scale.fit_transform(x_train[list(x_train.columns[2:12])])
    dataPoints[i] = (title, np.array(info[i]))
dataPoints[0]

                                                 title  top genre  year  bpm  \
10                                             Control          0  2020   99   
71                                       Main Kya Hoon          0  2009  135   
107                                            Jab Tak          0  2016  122   
101                                        Kaun Nachdi          0  2018  128   
42                                     Love Controller          0  2016  102   
63                          Photo (From "Luka Chuppi")          0  2019   95   
182                     Who Dat Boy (feat. A$AP Rocky)          2  2017  115   
70                                     Cheating on You          1  2019  123   
66          We Don't Talk Anymore (feat. Selena Gomez)          1  2016  100   
65                                         Ik Mulaqaat          0  2019   96   
165                                 Backseat Freestyle          4  2012   78   
131                        Change (feat.

('Control',
 array([ 1.23757584, -0.66818113, -0.68117291,  1.50012809,  0.04001307,
         0.22071481,  0.53104947, -1.38565382, -0.76005585,  0.12714147]))

In [22]:
from scipy import spatial

def ComputeDistance(a, b):
    dataA = a[1]
    dataB = b[1]
    similarityDistance = spatial.distance.cosine(dataA, dataB)
    return similarityDistance
    
ComputeDistance(dataPoints[11], dataPoints[2])

dataPoints[27]

('Lakk Mera Hit',
 array([ 0.36399289, -0.07718889,  1.26662091,  0.79486239,  0.48587296,
        -0.76869641,  2.04072995,  0.23676294, -0.86843675, -0.20342636]))

In [48]:
import operator

def getNeighbors(songID, K):
    distances = []
    for song in dataPoints:
        if (song != songID):
            dist = ComputeDistance(dataPoints[songID], dataPoints[song])
            distances.append((song, dist))
    distances.sort(key=operator.itemgetter(1))
    neighbors = []
    for x in range(K):
        neighbors.append(distances[x][0])
    return neighbors

K = 10
neighbors = getNeighbors(55, K)
for neighbor in neighbors:
    print (dataPoints[neighbor][0])

How Long
LA Girls
Empty Cups
Attention
Naah Goriye (From "Bala")
Kaun Nachdi
Slow It Down
Control
Coca Cola (From "Luka Chuppi")
Lakk Mera Hit


In [26]:
dataPoints

{0: ('Control',
  array([ 1.23757584, -0.66818113, -0.68117291,  1.50012809,  0.04001307,
          0.22071481,  0.53104947, -1.38565382, -0.76005585,  0.12714147])),
 1: ('Main Kya Hoon',
  array([-3.56713037,  0.66155141,  1.53714783, -1.06447445,  0.48587296,
          0.31965593,  0.81411456,  2.48010463, -0.97681766, -0.31361564])),
 2: ('Jab Tak',
  array([-0.50959005,  0.18137021, -1.11401598, -2.2185456 , -0.85170673,
         -0.47187304, -0.97863102, -0.96502725,  1.91333985, -0.64418347])),
 3: ('Kaun Nachdi',
  array([ 0.36399289,  0.4029923 ,  0.94198861,  0.79486239,  0.93173286,
         -1.06551978,  1.05000213, -0.78475872, -1.0490716 , -0.53399419])),
 4: ('Love Controller',
  array([-0.50959005, -0.55737008,  0.13040785,  0.73074733, -0.85170673,
         -0.37293192,  0.15362934, -0.62452003, -0.61554797, -0.53399419])),
 5: ('Photo (From "Luka Chuppi")',
  array([ 0.80078437, -0.81592919, -0.08601369,  0.6025172 ,  0.04001307,
          0.41859705, -0.97863102, -0.